name: Automatic Releases workflow sample
on:  
  # workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  test:
    name: "Test the application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: src
      - name: Build
        run: dotnet build
        working-directory: src
      - name: Test with the dotnet CLI
        run: dotnet test
        working-directory: src

  create-release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: "Create release"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: test
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3 
        with: 
          github-token: ${{ secrets.github_token }}
          output-file: 'false' 
          skip-commit: 'true'
          # version-file: '../packages/package.json'
          skip-tag: 'false'
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' && github.ref == 'refs/heads/main'}} 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ steps.changelog.outputs.tag }} 
          release_name: ${{ steps.changelog.outputs.tag }} 
          body: ${{ steps.changelog.outputs.clean_changelog }}
      
  publish-package-ghcr:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/primo391981/${{ vars.DEPARTMENT }}/${{ vars.APPLICATION_NAME }}
          tags: |
            type=semver,pattern={{raw}},value=${{ needs.create-release.outputs.tag }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}
          # tags: type=sha
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
  publish-package-acr:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ vars.ACR_SERVER }}/${{ vars.DEPARTMENT }}/${{ vars.APPLICATION_NAME }}
        tags: |
          # type=semver,pattern={{raw}},value=${{ needs.create-release.outputs.tag }}
          # type=ref,event=branch
          # type=ref,event=pr
          type=semver,pattern=v{{needs.create-release.outputs.major}}.{{needs.create-release.outputs.minor}}
        # tags: type=sha
    - name: Build container
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    # - name: 'Build Push to ACR'
    #   run: |
    #     docker build . -t ${{ vars.ACR_SERVER }}/${{ vars.DEPARTMENT }}/${{ vars.APPLICATION_NAME }}:${{ needs.create-release.outputs.tag }}
    #     docker push ${{ vars.ACR_SERVER }}/${{ vars.DEPARTMENT }}/${{ vars.APPLICATION_NAME }}:${{ needs.create-release.outputs.tag }} 

    # - uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'poc-auto-package'
    #     images: '${{ vars.ACR_SERVER }}/${{ vars.DEPARTMENT }}/${{ vars.APPLICATION_NAME }}:${{ needs.create-release.outputs.tag }}'

    # - name: Create URL to the run output
    #   id: vars
    #   run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

  create-comment:
    runs-on: ubuntu-latest
    needs: [publish-package-acr,create-release]
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:  
      - uses: actions/checkout@v3
      - name: 'Create issue'
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.create-release.outputs.tag }} 
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create-issue.outputs.number }} 
          body: |
            New container created and published!
            ## New tag: ${{ needs.create-release.outputs.tag }}
            ${{ needs.create-release.outputs.changelog }} 
          reactions: rocket

  # deploy-to-infra:
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   needs: [publish-package-acr,create-release]
  #   steps:
  #   # checkout the repo
  #   - name: 'Checkout Github Action'
  #     uses: actions/checkout@v3

  #   - name: 'Login via Azure CLI'
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #   - uses: azure/docker-login@v1
  #     with:
  #       login-server: ${{ vars.ACR_NAME }}
  #       username: ${{ secrets.ACR_USERNAME }}
  #       password: ${{ secrets.ACR_PASSWORD }}

  #   - name: 'Deploy to Azure'
  #     # env:
  #     #   SECRET: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}
  #     run: |
  #       container_name=${{ vars.ACR_SERVER }}/${{ vars.DEPARTMENT }}/${{ vars.APPLICATION_NAME }}:${{ needs.create-release.outputs.tag }}
  #       az deployment group create --resource-group RG-JMF-POC --template-file appservice.bicep --parameters appName=poc-auto-package acrName=${{ vars.ACR_NAME }} containerImage=$container_name
  #     working-directory: infrastructure
        
 
     