name: Automatic Releases workflow sample
on:  
  # workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  create-release:
    name: "Create release"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3 
        with: 
          github-token: ${{ secrets.github_token }}
          output-file: "false" 
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: ${{ steps.changelog.outputs.clean_changelog }}
          RELEASE_NAME: ${{ steps.changelog.outputs.tag }} 

        # uses: actions/create-release@v1
        # if: ${{ steps.changelog.outputs.skipped == 'false' }} 
        # env: 
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with: 
        #   tag_name: ${{ steps.changelog.outputs.tag }} 
        #   release_name: ${{ steps.changelog.outputs.tag }} 
        #   body: ${{ steps.changelog.outputs.clean_changelog }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/primo391981/automatic-releases/releases \
            -d '{"tag_name":"$RELEASE_NAME","target_commitish":"main","name":"$RELEASE_NAME","body":"$BODY","draft":false,"prerelease":false,"generate_release_notes":false}'
        
        
 
     