name: Deploy to cloud

on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  deploy-to-infra:
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    # needs: [publish-package-acr,create-release]
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.ACR_NAME }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: 'Deploy to Azure'
      # env:
      #   SECRET: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}
      run: |
        echo "Deploying container ${{ github.event.client_payload.slash_command.args.named.version }} in echo ${{ github.event.client_payload.slash_command.args.named.env }}"
        # echo ${{ github.event.client_payload.slash_command.command }}
        # echo ${{ github.event.client_payload.slash_command.args.all }}
        # echo ${{ github.event.client_payload.slash_command.args.unnamed.all }}
        # echo ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
        # echo ${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
        # echo ${{ github.event.client_payload.slash_command.args.named.env }}
        # echo ${{ github.event.client_payload.slash_command.args.named.version }}
        # echo ${{ github.event.client_payload.slash_command.args.named.reason }}
        # container_name=${{ vars.ACR_SERVER }}/${{ vars.DEPARTMENT }}/${{ vars.APPLICATION_NAME }}:${{ needs.create-release.outputs.tag }}
        # az deployment group create --resource-group RG-JMF-POC --template-file appservice.bicep --parameters appName=poc-auto-package acrName=${{ vars.ACR_NAME }} containerImage=$container_name
      working-directory: infrastructure
